### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by antonpanchenk0** [antonpanchenk0/lms_system#44]
## Description
Create login page according to mockups and implement login functionality

## Tasks
- [ ] The login page should be like in mockups
- [ ] The user should have the ability to login in
- [ ] The page should have correct catch and show all of the notifications, like success or error message of authorization
- [ ] Unit tests

## API
`POST /api-v1/user/login/`

```bash
{
  "email": "example@something.com",
  "password": "qwerty123"
}
```

**Responses**

Status 200
```bash
{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMmRzYWRhczM0NTY3ODkwIiwibmFtZSI6IkpvaG4gZGFzZGFzZGFzZGFzZERvZSIsImlhdCI6MTUxNjIzOTAyMn0.yJCKpe3gG6O9wtx6uKzl3Frfe9LKv1ooxMj3erRranw"
}
```

Status 400 | Status 401
```bash
{
  "message": "Error description"
}
```

## Links
Mockups:
https://www.figma.com/file/PxkEfzq0hXrBvTAtChffQ1/LMS?node-id=2%3A535
