### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by antonpanchenk0** [antonpanchenk0/lms_system#45]
## Description
Create the LMS navigation bar according to mockups

## Tasks
- [ ] The navigation bar should be like in mockups
- [ ] The navigation bar should show active links correctly
- [ ] The navigation bar should give the ability to user logout
- [ ] Make the code easy styling for responsive in future 
- [ ] Unit tests

## Links
Mockups:
https://www.figma.com/file/PxkEfzq0hXrBvTAtChffQ1/LMS?node-id=9%3A31
