### ISSUE TITLE
Notification enhancements 

### ISSUE THREAD

**Issue by antonpanchenk0** [antonpanchenk0/lms_system#46]
## Description
Improve notification component according to mockups

## Tasks
- [ ] Notifications should be like in mockups
- [ ] The notification component should contain `content` field
- [ ] Notification should close automatically after 10 seconds
- [ ] Make the code easy styling for responsive in future 
- [ ] Unit tests

## Links
Mockups:
https://www.figma.com/file/PxkEfzq0hXrBvTAtChffQ1/LMS?node-id=45%3A882
