### ISSUE TITLE
Overview/Basic setup

### ISSUE THREAD

**Issue by antonpanchenk0** [antonpanchenk0/lms_system#48]
## Description
Create a basic folder structure for the overview page

## Tasks
- [ ] Create `OverviewPage` folder in the `pages` folder
- [ ] Create `sagas.js` with watcher saga
- [ ] Create `reducer.js` with basic reducer and selectors
- [ ] Create `OverviewPage.jsx` with basic react component
- [ ] Create `OverviewPage.scss` or `OverviewPage.style.js` with basic styles settings
