### ISSUE TITLE
Overview/Achievements 

### ISSUE THREAD

**Issue by antonpanchenk0** [antonpanchenk0/lms_system#49]
## Description
Create the achievements section of the overview page according to mockups

## Tasks
- [ ] The achievements section of the overview page should be like in mockups
- [ ] The achievement should show got and not get yet states
- [ ] Make the code easy styling for responsive in future 
- [ ] Unit tests

## API
In progress ...
```

## Links
Mockups:
https://www.figma.com/file/PxkEfzq0hXrBvTAtChffQ1/LMS?node-id=9%3A31
